### ISSUE TITLE
v1.0

### ISSUE THREAD

**Issue by JestDotty** [screepers/node-screeps-api#3]
forced dependency to get v1.0 because I wanted to play with it `"screeps-api": "screepers/node-screeps-api#v1.0",`

test console.js
```js
const ScreepsAPI = require('screeps-api')
const creds = require('./creds')

const api = new ScreepsAPI(creds)
```

```
PS D:\Dropbox\git\screep.serfinity> node console
module.js:471
    throw err;
    ^

Error: Cannot find module './build/'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Dropbox\git\screep.serfinity\node_modules\screeps-api\index.js:1:80)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

I understand it's not done, but just reporting

**Comment by ags131** [comment]
Thanks for the report, straight git dependencies are finicky, and in this case doesn't trigger the build properly, while not a perfect solution, you can cd into `node_modules/screeps-api` and run `npm install` to get it to build. If you have any thoughts on how to make it build properly when used as a git dep, I'm all ears :)

**Comment by JestDotty** [comment]
yeah, I tried to poke around to find out what's up. Never used either of these tho (preinstall or gulp)

actually seems I don't have a src folder when I npm install it O-o

**Comment by JestDotty** [comment]
ok i understand what happened

you have a file `.npmignore` that is ignoring `src`, so npm never picks up your `src` folder if one npm installs the module (thru git or npm or file system)

`build` script will fail, because npm never got the `src` folder
and because v1.0 was never published on npm registry, `prepublish` script is never run to make the build either

no `src`, no `build`.

**Comment by JestDotty** [comment]
if I fix that then it complains I don't have gulp installed, so that build script was never supposed to be run on the user's machine anyway...

**Comment by ags131** [comment]
Yea, preinstall only runs if npm install is ran locally, when I do npm
publish build is included but it exclud s SRC on purpose to keep sizes
smaller. When using a git repo for npm install, it's odd since it treats it
the same as if in npm, and I gitignore build to keep history cleaner

**Comment by JestDotty** [comment]
k, did a workaround here: https://github.com/JestDotty/node-screeps-api/tree/v1.0

build folder ends up on git but installed folder looks like this afterwards (no src):
![image](https://cloud.githubusercontent.com/assets/4729968/26514849/ca44f3e4-4242-11e7-9f94-0b774d589ecc.png)

**Comment by JestDotty** [comment]
either this changed something or v1.0 docs aren't accurate?

![image](https://cloud.githubusercontent.com/assets/4729968/26514928/7f3acaee-4243-11e7-9536-1767f1b691f8.png)

Seems ScreepsAPI overly nested itself...

**Comment by ags131** [comment]
Closing. v1.0 is released and on npm.
