### ISSUE TITLE
"[object Object]" returned when subscribing to memory

### ISSUE THREAD

**Issue by DomNomNom** [screepers/node-screeps-api#32]
screepsApi.socket.subscribe('memory/stats',(event)=>{
        console.log('stats', JSON.stringify(event))
    })

Results in

    stats {"channel":"memory/stats","id":"57909b057d880b5773e95d25","type":"user","data":"[object Object]"}

I double checked that my memory indeed contains an object at that memory path, not this string.
Is this how it's returned from the screeps server or is node-screeps-api doing something weird?

**Comment by ags131** [comment]
thats a screeps server thing
to get the right value you have to call memory.get with the path
