### ISSUE TITLE
Can't install on node 10, utf-8-validate package won't install

### ISSUE THREAD

**Issue by LordZardeck** [screepers/node-screeps-api#36]
if I manually update the lock file to use version 4 of the package, the install is successful. Please update utf-8-validate

**Comment by LordZardeck** [comment]
Or remove it, doesn't seem like it's used

**Comment by ags131** [comment]
At one point it was a peer dependency of another package, WS IIRC, I would
be open to a PR updating it, otherwise I'll update it next time I have a
chance.
