### ISSUE TITLE
Is it possible to execute arbitrary commands using this API?

### ISSUE THREAD

**Issue by rgrannell1** [screepers/node-screeps-api#38]
I'm planning to write a Google Function to:

- Pull events (and clear the array) from `Memory.events` periodically
- Post these events to a local database

Is it possible to retrieve `Memory.events` (it appears to be based on the docs) and then empty `Memory.events` (did spot this in Endpoints.md)

Thanks for your help

**Comment by Hiryus** [comment]
You can use something like:
```javascript
events = await api.memory.get('events')
```
... to pull data and right after:
```javascript
api.memory.set('events', [])
```
... to clear events.
There is a small chance of losing events if the `set()` occurs at the same time of a new tick though.

I've not tried it, but you may be able to subscribe to socket memory events instead:
```
api.socket.subscribe('memory/events',(event)=>{
	console.log('stats', event.data)
})
```

**Comment by rgrannell1** [comment]
Thanks for the quick response! That looks perfect, I'm not especially worried about race-conditions in this case
