### ISSUE TITLE
api.memory.get()   .then(memory => {     fs.writeFileSync('memory.json', JSON.stringify(memory))   })   .catch(err => console.error(err));

### ISSUE THREAD

**Issue by bubble93** [screepers/node-screeps-api#49]
error: Error: Rate limit exceeded, retry after 7075614ms or disable rate limiting using this link: https://screeps.com/a/#!/account/auth-tokens/noratelimit?token=9700ca14
    at ScreepsAPI.req (/Users/yanglei/Documents/GitHub/bubble-screeps/node_modules/screeps-api/dist/ScreepsAPI.js:609:13)

**Comment by ags131** [comment]
The error tells you the exact problem, you exceeded the rate limits. See: https://docs.screeps.com/auth-tokens.html#Rate-Limiting
