### ISSUE TITLE
authentication errors

### ISSUE THREAD

**Issue by screeps-qnz** [screepers/node-screeps-api#51]
trying to integrate updating my badge into my deployment i ran into the following issue:

i wanted to integrate the badge update script in a way that it uses the screeps.json that is being used by the ts-starter rollup configuration. so my config looked something like this:

``` {"otherstuff": {},
"pserver": {
    "email": "qnz",
    "password": "test",
    "protocol": "http",
    "hostname": "localhost",
    "port": 21025,
    "path": "/",
    "branch": "default"
  }}
```

i then authenticated using the pserver object that got parsed from json like so: 

```
const api = new ScreepsAPI(cfg[dest]);
api.auth(cfg[dest].email, cfg[dest].password, cfg[dest]);
```

the auth would fail and everything else would be http401. api.__authed was undefined, api.opts were set correctly

```
__authed: undefined
opts: {"protocol":"http","hostname":"127.0.0.1","port":21025,"path":"/","email":"qnz","password":"test","branch":"default","secure":false,"pathname":"/","url":"http://127.0.0.1:21025/"}       
(node:388524) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Not Authorized
```

i got it working like this though:

```
const api = new ScreepsAPI(cfg[dest]);
api.auth(cfg[dest].email, cfg[dest].password, cfg[dest]);
const res = await api.raw.auth.signin(cfg[dest].email, cfg[dest].password);
```

the raw call somehow worked perfectly fine, and subsequent calls would work fine too. (the "OK." is the end of my script) 

```
__authed: undefined
opts: {"protocol":"http","hostname":"127.0.0.1","port":21025,"path":"/","email":"qnz","password":"test","branch":"default","secure":false,"pathname":"/","url":"http://127.0.0.1:21025/"}       
OK.
```

im not quite sure whether this is a bug or whether i did something wrong, but i debugged this for a while and i suspect it is some weirdness in screeps-api (maybe its related to api.__authed staying undefined?). could not really find the cause sadly so im reporting it here

some version numbers:
- screeps-api": "^1.9.1"
- servers i tested this with were screeps-launcher v1.9.6 running screeps server 4.1.6 via http and s+2 via https

**Comment by ags131** [comment]
`api.auth` returns a promise, so you need to `await` it too. Also, its not required to pass the options in again in `auth`
Ex:
```javascript
const api = new ScreepsAPI(cfg[dest]);
await api.auth(cfg[dest].email, cfg[dest].password);
const me = await api.me();
```
---------------------
Another option is to use the newer config support, 
```javascript
const api = await ScreepsAPI.fromConfig('botarena', 'screeps-cap') 
const { twitch, chatTimeout = 60 } = api.appConfig
// no need to call auth, its automatically done
const me = await api.me()
```
with a config something like this: (See the [Unified Credentials Format](https://github.com/screepers/screepers-standards/blob/master/SS3-Unified_Credentials_File.md) page for details on file location and name)
```yaml
servers:
  botarena:
    host: botarena.screepspl.us
    secure: true
    port: 443
    username: ChangeMe
    password: ChangeMe
configs:
  screeps-cap:
    chatTimeout: 30
```
Using the config can be convenient, if you have one in your home folder, can just clone a repo and run (maybe using an argument for which server to use) and thats it, no extra setup needed :D

**Comment by screeps-qnz** [comment]
ahh, so thats why the raw call worked haha

fixed and working

and yeah, im aware of the unified credentials stuff, but avoiding it out of pure laziness (plus i really only have my bot as the one repo that would use it on each computer)

thanks!
