### ISSUE TITLE
Cannot install in node 12, needs bufferutil 4.x

### ISSUE THREAD

**Issue by SystemParadox** [screepers/node-screeps-api#54]
Installing on node12 results in build errors from `bufferutil -> nan`. Updating to `bufferutil@4.x` should fix it.

```
In file included from ../../nan/nan_new.h:189,
                 from ../../nan/nan.h:203,
                 from ../src/bufferutil.cc:7:
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::Function>::return_t Nan::imp::Factory<v8::Function>::New(Nan::FunctionCallback, v8::Local<v8::Value>)’:
../../nan/nan_implementation_12_inl.h:105:32: error: no matching function for call to ‘v8::Function::New(v8::Isolate*&, void (&)(const v8::FunctionCallbackInfo<v8::Value>&), v8::Local<v8::Object>&)’
                           , obj));
```

**Comment by SystemParadox** [comment]
Actually I searched the code and bufferutil isn't even used?

**Comment by ags131** [comment]
buffer util is an optionalDependency for ws, it uses them if available to improve websocket performance.

**Comment by SystemParadox** [comment]
Even if you *can* ignore these errors, it's still really annoying and very confusing for people. Can you really ignore these anyway? Could this cause issues with other packages that need building or have postinstall scripts?

Node 10 is pretty old now. If we're not willing to at least keep the optional packages up to date with the latest LTS (which is Node 12) then we should just remove them entirely from the package.json.

I didn't have any issues after forcing it onto bufferutil 4, but I couldn't confirm whether ws was able to make use of it or not.
