### ISSUE TITLE
Reconnect goes mental if the connection is refused

### ISSUE THREAD

**Issue by SystemParadox** [screepers/node-screeps-api#64]
1. Start private server
2. Create websocket connection with `api.socket.connect()`
3. Stop the server

Reconnect goes mental:

```
  screepsapi:socket disconnected +695ms
  screepsapi:socket error Error: connect ECONNREFUSED 192.168.8.2:21025 +112ms
  screepsapi:socket disconnected +0ms
  screepsapi:socket reconnect 1/10 +1ms
  screepsapi:socket error Error: connect ECONNREFUSED 192.168.8.2:21025 +109ms
  screepsapi:socket disconnected +0ms
  screepsapi:socket reconnect 1/10 +0ms
  screepsapi:socket error Error: connect ECONNREFUSED 192.168.8.2:21025 +99ms
  screepsapi:socket disconnected +1ms
  screepsapi:socket reconnect 2/10 +0ms
  screepsapi:socket error Error: connect ECONNREFUSED 192.168.8.2:21025 +6ms
  screepsapi:socket disconnected +1ms
  screepsapi:socket reconnect 1/10 +0ms
  screepsapi:socket error Error: WebSocket was closed before the connection was established +104ms
  screepsapi:socket error Error: connect ECONNREFUSED 192.168.8.2:21025 +0ms
  screepsapi:socket disconnected +0ms
  screepsapi:socket disconnected +1ms
  screepsapi:socket reconnect 1/10 +0ms
  screepsapi:socket reconnect 1/10 +0ms
```

What's happening is that the socket close event is being fired immediately when the connection fails, which triggers another call to `this.reconnect()`, but it never checks to see if it's currently reconnecting and so retries immediately each time. Additionally, the `close` event fires before the `disconnect` event which cleans up the event listeners so the original reconnection "thread" often makes at least one retry before its listeners are killed, with each retry guaranteeing at least one extra connection attempt. It's not quite a fork bomb, but it slowly accumulates more simultanous connection attempts as time goes on.

I'm working on a PR to fix this but welcome any comments about how this should be fixed.

**Comment by ags131** [comment]
Just took a quick look at the code, adding `if (this.reconnecting) return` at the top of `reconnect()` is probably enough to fix this
