### ISSUE TITLE
axios needs updated

### ISSUE THREAD

**Issue by EsoterikStare** [screepers/node-screeps-api#75]
The current version of axios has a known moderate vulnerability, documented [here](https://github.com/advisories/GHSA-wf5p-g6vw-rhxx). It's also grossly out of date, in general.

**Comment by AlinaNova21** [comment]
Fixed in v1.16.1, Dependencies overall could probably use bringing up to more modern versions, but also need to be careful of people still running older node for the PS. And I don't have the time to test lately, PRs are welcome though!

**Comment by EsoterikStare** [comment]
Thanks! 

I'm just starting to wade into Screeps and the library ecosystem around it. I did pull this down and poke at it and updating seems safe, but I'm not 100% sure it wouldn't break others.

It would be nice to at least get everyone up to the lowest node LTS that's still at least in maintenance support. Since active support for `v16.x` was dropped last year `v18.x` will be the lowest actively supported LTS for a while longer. But I'm not sure how likely libraries in this community are to be that up-to-date. Seeems like it might be a stretch, based on what I'm seeing so far... =)

It's easy enough to add an `engines` config to `package.json` to help people know that if they're below a certain node/npm version, they might have a bad time. Yarn is a little more strict about the version declared there, though...

Let me know what you think about updating deps, running existing tests, and configuring minimum engine versions and I can put together an MR some time soonish, most likely.

**Comment by EsoterikStare** [comment]
Side note: I'm not even using this directly, but through [rollup-plugin-screeps-world](https://github.com/screepers/rollup-plugin-screeps-world) which is still on `v1.11.0`, so now I have to go see if I can get them to update. =)
